import { sha256 } from "@noble/hashes/sha2.js";
import { bytesToHex, utf8ToBytes } from "@noble/hashes/utils.js";
import { z } from "zod";

import { idSchema } from "./common.js";

/**
 * Canonical idempotency key generator for outbound dispatches (IF-01).
 *
 * The key is stamped into `messages.idempotency_key` (UNIQUE partial index)
 * and the job's `payload.idempotencyKey`, so a retry of the same logical
 * dispatch — whether after a worker crash, queue redrive, or duplicate
 * enqueue — collapses onto the same row and is skipped by the worker
 * dispatch guard.
 *
 * Three kinds today (extend as new senders appear):
 * - `campaign_step` — keyed by (campaign, recipient, step).
 * - `manual` — keyed by (user, conversation, clientNonce) where clientNonce
 *   is a UUID generated by the UI per compose action, surviving optimistic
 *   send retries.
 * - `chatbot_reply` — keyed by (rule, triggering inbound externalId).
 */

export const campaignStepKeyInputSchema = z.object({
  kind: z.literal("campaign_step"),
  userId: idSchema,
  campaignId: idSchema,
  recipientId: idSchema,
  stepId: z.string().min(1),
});

export const manualSendKeyInputSchema = z.object({
  kind: z.literal("manual"),
  userId: idSchema,
  conversationId: idSchema,
  clientNonce: z.string().min(8),
});

export const chatbotReplyKeyInputSchema = z.object({
  kind: z.literal("chatbot_reply"),
  userId: idSchema,
  ruleId: idSchema,
  triggerMessageExternalId: z.string().min(1),
});

export const idempotencyKeyInputSchema = z.discriminatedUnion("kind", [
  campaignStepKeyInputSchema,
  manualSendKeyInputSchema,
  chatbotReplyKeyInputSchema,
]);

export type CampaignStepKeyInput = z.infer<typeof campaignStepKeyInputSchema>;
export type ManualSendKeyInput = z.infer<typeof manualSendKeyInputSchema>;
export type ChatbotReplyKeyInput = z.infer<typeof chatbotReplyKeyInputSchema>;
export type IdempotencyKeyInput = z.infer<typeof idempotencyKeyInputSchema>;

/**
 * Returns a deterministic, opaque key in the form `<kind>:<16-hex>`. Truncated
 * to 16 hex chars (64 bits) — collision risk negligible at our volumes
 * and keeps the column human-scannable in the SQLite browser.
 */
export function idempotencyKey(input: IdempotencyKeyInput): string {
  // Canonical serialization so equivalent inputs hash identically regardless
  // of property declaration order.
  const canonical = JSON.stringify(input, Object.keys(input).sort());
  const digest = bytesToHex(sha256(utf8ToBytes(canonical))).slice(0, 16);
  return `${input.kind}:${digest}`;
}

/**
 * Reads the canonical key from a job payload. Falls back to a deterministic
 * `legacy:job:<id>` value so pre-IF-01 jobs in flight at deploy time still
 * pass through the dispatch guard without skipping legitimate sends.
 */
export function extractIdempotencyKeyFromJobPayload(
  payload: unknown,
  jobId: number,
): string {
  if (payload && typeof payload === "object" && "idempotencyKey" in payload) {
    const value = (payload as { idempotencyKey?: unknown }).idempotencyKey;
    if (typeof value === "string" && value.length > 0) {
      return value;
    }
  }
  return `legacy:job:${jobId}`;
}
